### ISSUE TITLE
I subscribed to new version

### ISSUE THREAD

**Issue by ScreamZ** [stephentuso/ts-graphql#13]
Hello, this lib seems promising and active not like the other tsGraph lib ^^
So I subscribed to new releases.

The thing is we jumped from 3.0 to 5.0 very quickly.

May I suggest you to simply add a beta flag so you are free to breaking change in the version, you don't have much stars and user atm this could be better :-)

Regards

**Comment by stephentuso** [comment]
Thanks :) This is very true, in retrospect I should have manually managed the version below 1.0 and not used [semantic-release](https://github.com/semantic-release/semantic-release) until it was stable. However, at this point it's hard to undo (can't unpublish from npm) and there shouldn't be any more breaking changes for a while, so I'm going to leave as is. Thanks for the suggestion!

**Comment by ScreamZ** [comment]
All right that's fine as long we aren't on version 477 xD

I keep subscribing, good luck
