### ISSUE TITLE
Type extensions based on decorators

### ISSUE THREAD

**Issue by boschni** [stephentuso/ts-graphql#17]
Hi! I really like your approach to having a thin decorator layer around `graphql-js`. The API is pretty concise, but the current way of creating modular fields feels a bit out of sync with the rest of the library. Would you be open to discuss type extensions based on decorators?

Something in the lines of:

```ts
// Query.ts
@ObjectType()
class Query {}

// Author.ts
@ObjectType()
class Author {
  @Field({ type: TSGraphQLID })
  id: ID;
}

@Args()
class AuthorArgs {
  @Arg({ type: TSGraphQLID })
  id: ID;
}

@Extend({ type: Query })
class AuthorQueryExtension {
  @Field({ type: Author, args: AuthorArgs })
  author(query, args, context) {
    // ...
  }
}
```

The `Extend` decorator is based on [extending types in Apollo](https://www.apollographql.com/docs/graphql-tools/generate-schema#extend-types) and [extendSchema in graphql-js](https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/extendSchema-test.js) .

**Comment by stephentuso** [comment]
Thanks! Yes - that's a good point and would be a good addition. It'll have to be a little different than a normal object type class, the source type won't be an instance of the same class so the resolvers should probably be static methods. There are a few other details to work out - I'll keep thinking about it

**Comment by boschni** [comment]
From a technical point of view they should probably indeed be static methods, but from a user perspective it might make sense to keep the syntax for defining fields the same as object type classes. This keeps the library API a bit smaller and more predictable. Minor point though :)
